apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: project-service
    profile: prod
spec:
  selector:
    matchLabels:
      app: project-service
      profile: prod
  # 앱이 Ready 상태가 될 때까지 기다리는 시간
  minReadySeconds: 10
  # 롤링 업데이트:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # 롤링 업데이트시 스케일아웃할 최대 pod 수
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      name: project-pod
      labels:
        app: project-service
        profile: prod
    spec:
      containers:
        - name: project-service
          image: ${ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
        - name: mysql
          image: mysql:8.0.34
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "11111111"
            - name: MYSQL_DATABASE
              value: project-service
            - name: LC_ALL
              value: C.UTF-8
          resources:
            requests:
              memory: "1Gi"
          volumeMounts:
            - name: lotdiz-project-storage
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: lotdiz-project-storage
          persistentVolumeClaim:
            claimName: project-efs-claim
        - name: mysql-config
          configMap:
            name: mysql-config
      restartPolicy: Always

