spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://config-service:8888
  # rabbitmq settings
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
  # DB settings
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project-service
    username: root
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

cloud:
  aws:
    credentials:
      ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    sqs:
      project-due-date-event-queue:
        name: LotdizProjectDueDateEventQueue
        url: ${AWS_SQS_ENDPOINT}/LotdizProjectDueDateEventQueue

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
