spring:
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://127.0.0.1:8888
  # rabbitmq settings
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # h2 settings
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:project-service;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    # Bean이 생성되기 전에 ddl 실행
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

cloud:
  aws:
    credentials:
      ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    sqs:
      project-due-date-event-queue:
        name: LotdizProjectDueDateEventQueue
        url: ${AWS_SQS_ENDPOINT}/LotdizProjectDueDateEventQueue
    sns:
      project-due-date-notification-topic:
        name: LotdizProjectDueDateNotificationTopic
        url: ${AWS_SNS_ENDPOINT}:LotdizProjectDueDateNotificationTopic

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

endpoint:
  funding-service: ${FUNDING_SERVICE_ENDPOINT}
