-- H2 2.1.214;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '0611ab41f36637ad' HASH '51f72a27360b3dd42652e754f2d805fe19488ace5dece8da589fbf2840de44fa' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."banner"(
    "banner_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "banner_image_url" CHARACTER VARYING(255) NOT NULL,
    "banner_url" CHARACTER VARYING(255) NOT NULL
);        
ALTER TABLE "PUBLIC"."banner" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("banner_id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.banner;  
CREATE MEMORY TABLE "PUBLIC"."category"(
    "category_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) DEFAULT ON NULL NOT NULL,
    "category_name" CHARACTER VARYING(255) NOT NULL
);           
ALTER TABLE "PUBLIC"."category" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("category_id");            
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.category;
INSERT INTO "PUBLIC"."category" VALUES
(1, U&'\d328\c158'),
(2, U&'\c74c\c2dd'),
(3, U&'\ac00\c804'),
(4, U&'\b3c4\c11c');
CREATE MEMORY TABLE "PUBLIC"."lotdeal"(
    "lotdeal_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "lotdeal_due_time" TIMESTAMP,
    "lotdeal_start_time" TIMESTAMP,
    "project_id" BIGINT
);       
ALTER TABLE "PUBLIC"."lotdeal" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("lotdeal_id");              
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.lotdeal; 
INSERT INTO "PUBLIC"."lotdeal" VALUES
(1, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-12-09 10:59:59', TIMESTAMP '2023-11-08 23:59:59', 1),
(2, TIMESTAMP '2023-10-08 23:59:59', TIMESTAMP '2023-10-08 23:59:59', TIMESTAMP '2023-12-09 10:59:59', TIMESTAMP '2023-10-08 23:59:59', 2);               
CREATE MEMORY TABLE "PUBLIC"."maker"(
    "maker_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "maker_email" CHARACTER VARYING(255) NOT NULL,
    "maker_home_url" CHARACTER VARYING(255),
    "maker_kakao_url" CHARACTER VARYING(255),
    "maker_name" CHARACTER VARYING(255) NOT NULL,
    "maker_phone_number" CHARACTER VARYING(255) NOT NULL,
    "maker_sns_url" CHARACTER VARYING(255),
    "member_id" BIGINT NOT NULL
);               
ALTER TABLE "PUBLIC"."maker" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("maker_id");  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.maker;   
INSERT INTO "PUBLIC"."maker" VALUES
(1, TIMESTAMP '2023-12-11 23:59:59', TIMESTAMP '2023-12-11 23:59:59', 'cso6005@nvaer.com', '/home', '/kakao', 'soyoung', '01033344455', '/sns', 1);      
CREATE MEMORY TABLE "PUBLIC"."product"(
    "product_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 4) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "product_current_stock_quantity" BIGINT NOT NULL,
    "product_description" CHARACTER VARYING(255) NOT NULL,
    "product_name" CHARACTER VARYING(255) NOT NULL,
    "product_price" BIGINT NOT NULL,
    "product_registered_stock_quantity" BIGINT NOT NULL,
    "project_id" BIGINT
);       
ALTER TABLE "PUBLIC"."product" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("product_id");              
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.product; 
INSERT INTO "PUBLIC"."product" VALUES
(1, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', 20, U&'\c637 \c88b\c544\c694!!', U&'\ae34\ae34 \c154\ce20', 100000, 50, 1),
(2, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', 50, U&'\c637 \c88b\c544\c694!!', U&'\c9e7\c740 \c154\ce20', 100000, 50, 1),
(3, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', 0, U&'\c637 \c88b\c544\c694!!', U&'\c0c9\c774 \b354 \c9c4\d55c \c154\ce20', 100000, 50, 1);
CREATE MEMORY TABLE "PUBLIC"."project"(
    "project_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "project_description" CHARACTER VARYING(255) NOT NULL,
    "project_due_date" TIMESTAMP NOT NULL,
    "project_is_authorized" BOOLEAN NOT NULL,
    "project_name" CHARACTER VARYING(255) NOT NULL,
    "project_status" CHARACTER VARYING(255) DEFAULT 'PENDING' NOT NULL,
    "project_story_image_url" CHARACTER VARYING(255) NOT NULL,
    "project_tag" CHARACTER VARYING(255) NOT NULL,
    "project_target_amount" BIGINT NOT NULL,
    "category_id" BIGINT,
    "maker_id" BIGINT
);               
ALTER TABLE "PUBLIC"."project" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_ED" PRIMARY KEY("project_id");             
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.project; 
INSERT INTO "PUBLIC"."project" VALUES
(1, TIMESTAMP '2023-12-11 23:59:59', TIMESTAMP '2023-12-11 23:59:59', U&'\c88b\c544\c694', TIMESTAMP '2023-12-11 23:59:59', TRUE, U&'\c18c\b77c\c0c9 \c154\ce20 \d310\b9e4', 'PROCESSING', '/story-image', U&'\c154\ce20', 10000000, 1, 1),
(2, TIMESTAMP '2023-12-11 23:59:59', TIMESTAMP '2023-12-11 23:59:59', U&'\c88b\c544\c694', TIMESTAMP '2023-12-11 23:59:59', TRUE, U&'\d30c\b780\c0c9 \c154\ce20 \d310\b9e4', 'PROCESSING', '/story-image', U&'\c154\ce20', 10000000, 1, 1),
(3, TIMESTAMP '2023-12-11 23:59:59', TIMESTAMP '2023-12-11 23:59:59', U&'\c88b\c544\c694', TIMESTAMP '2023-12-11 23:59:59', TRUE, U&'\c640\c778\c0c9 \c154\ce20 \d310\b9e4', 'PROCESSING', '/story-image', U&'\c154\ce20', 10000000, 1, 1),
(4, TIMESTAMP '2023-12-11 23:59:59', TIMESTAMP '2023-12-11 23:59:59', U&'\c88b\c544\c694', TIMESTAMP '2023-12-11 23:59:59', FALSE, U&'\bc18\bc14\c9c0 \d310\b9e4', 'PROCESSING', '/story-image', U&'\c154\ce20', 10000000, 1, 1),
(5, TIMESTAMP '2023-12-11 23:59:59', TIMESTAMP '2023-12-11 23:59:59', U&'\c88b\c544\c694', TIMESTAMP '2023-12-11 23:59:59', TRUE, U&'\b9db\c788\b294 \b538\ae30', 'PROCESSING', '/story-image', U&'\c154\ce20', 10000000, 2, 1);             
CREATE MEMORY TABLE "PUBLIC"."project_image"(
    "project_image_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "project_image_is_thumbnail" BOOLEAN NOT NULL,
    "project_image_url" CHARACTER VARYING(255) NOT NULL,
    "project_id" BIGINT
);     
ALTER TABLE "PUBLIC"."project_image" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("project_image_id");  
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.project_image;           
INSERT INTO "PUBLIC"."project_image" VALUES
(1, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', TRUE, '/thum-url', 1),
(2, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', FALSE, '/img-url-1', 1),
(3, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', FALSE, '/img-url-2', 1),
(4, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', FALSE, '/img-url-3', 1),
(5, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', FALSE, '/img-url-4', 1);     
CREATE MEMORY TABLE "PUBLIC"."support_signature"(
    "support_signature_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "member_id" BIGINT NOT NULL,
    "support_signature_content" CHARACTER VARYING(500) NOT NULL,
    "project_id" BIGINT
);       
ALTER TABLE "PUBLIC"."support_signature" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_AB" PRIMARY KEY("support_signature_id");         
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.support_signature;       
INSERT INTO "PUBLIC"."support_signature" VALUES
(1, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', 1, U&'\ae30\b300\b429\b2c8\b2e4.!!', 1),
(2, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', 1, U&'\ae30\b300\b429\b2c8\b2e4.!!', 2),
(3, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', 2, U&'\ae30\b300\b429\b2c8\b2e4.!!', 1),
(4, TIMESTAMP '2023-10-09 23:59:59', TIMESTAMP '2023-10-09 23:59:59', 2, U&'\ae30\b300\b429\b2c8\b2e4.!!', 2);               
ALTER TABLE "PUBLIC"."maker" ADD CONSTRAINT "PUBLIC"."UK_7es8ucetmkkfskeuy5nbtfnwy" UNIQUE("member_id");      
ALTER TABLE "PUBLIC"."project" ADD CONSTRAINT "PUBLIC"."FKe0w7gh0rpmxo35nltk6g8517q" FOREIGN KEY("category_id") REFERENCES "PUBLIC"."category"("category_id") NOCHECK;        
ALTER TABLE "PUBLIC"."project" ADD CONSTRAINT "PUBLIC"."FKcf3xn6841jcaijvqesp19gjox" FOREIGN KEY("maker_id") REFERENCES "PUBLIC"."maker"("maker_id") NOCHECK; 
ALTER TABLE "PUBLIC"."project_image" ADD CONSTRAINT "PUBLIC"."FKsrkbi9ax581cp14a13mbk9qtm" FOREIGN KEY("project_id") REFERENCES "PUBLIC"."project"("project_id") NOCHECK;     
ALTER TABLE "PUBLIC"."product" ADD CONSTRAINT "PUBLIC"."FKncxhj0xapt1bdqasvd92mi1ee" FOREIGN KEY("project_id") REFERENCES "PUBLIC"."project"("project_id") NOCHECK;           
ALTER TABLE "PUBLIC"."support_signature" ADD CONSTRAINT "PUBLIC"."FK34p33d4109n7ix2d8nkmoardo" FOREIGN KEY("project_id") REFERENCES "PUBLIC"."project"("project_id") NOCHECK; 
ALTER TABLE "PUBLIC"."lotdeal" ADD CONSTRAINT "PUBLIC"."FK66bkemghgbquls540w5dhhr80" FOREIGN KEY("project_id") REFERENCES "PUBLIC"."project"("project_id") NOCHECK;           
