-- H2 2.1.214;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '64984a69631128af' HASH 'b6054fd1f0578c377dd722323e1476584118cb437ec0ef8755d503655d470527' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."banner"(
    "banner_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "banner_image_url" CHARACTER VARYING(255) NOT NULL,
    "banner_url" CHARACTER VARYING(255) NOT NULL
);        
ALTER TABLE "PUBLIC"."banner" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("banner_id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.banner;  
CREATE MEMORY TABLE "PUBLIC"."category"(
    "category_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "category_name" CHARACTER VARYING(255) NOT NULL
);          
ALTER TABLE "PUBLIC"."category" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("category_id");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.category;
CREATE MEMORY TABLE "PUBLIC"."lotdeal"(
    "lotdeal_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "lotdeal_due_time" TIMESTAMP,
    "lotdeal_start_time" TIMESTAMP,
    "project_id" BIGINT
);      
ALTER TABLE "PUBLIC"."lotdeal" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("lotdeal_id");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.lotdeal; 
CREATE MEMORY TABLE "PUBLIC"."maker"(
    "maker_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "maker_email" CHARACTER VARYING(255) NOT NULL,
    "maker_home_url" CHARACTER VARYING(255),
    "maker_kakao_url" CHARACTER VARYING(255),
    "maker_name" CHARACTER VARYING(255) NOT NULL,
    "maker_phone_number" CHARACTER VARYING(255) NOT NULL,
    "maker_sns_url" CHARACTER VARYING(255),
    "member_id" BIGINT NOT NULL
);              
ALTER TABLE "PUBLIC"."maker" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("maker_id");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.maker;   
CREATE MEMORY TABLE "PUBLIC"."product"(
    "product_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "product_current_stock_quantity" BIGINT NOT NULL,
    "product_description" CHARACTER VARYING(255) NOT NULL,
    "product_name" CHARACTER VARYING(255) NOT NULL,
    "product_price" BIGINT NOT NULL,
    "product_registered_stock_quantity" BIGINT NOT NULL,
    "project_id" BIGINT
);      
ALTER TABLE "PUBLIC"."product" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("product_id");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.product; 
CREATE MEMORY TABLE "PUBLIC"."project"(
    "project_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "project_description" CHARACTER VARYING(255) NOT NULL,
    "project_due_date" TIMESTAMP NOT NULL,
    "project_is_authorized" BOOLEAN NOT NULL,
    "project_name" CHARACTER VARYING(255) NOT NULL,
    "project_status" CHARACTER VARYING(255) DEFAULT 'PENDING' NOT NULL,
    "project_story_image_url" CHARACTER VARYING(255) NOT NULL,
    "project_tag" CHARACTER VARYING(255) NOT NULL,
    "project_target_amount" BIGINT NOT NULL,
    "category_id" BIGINT,
    "maker_id" BIGINT
);              
ALTER TABLE "PUBLIC"."project" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_ED" PRIMARY KEY("project_id");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.project; 
CREATE MEMORY TABLE "PUBLIC"."project_image"(
    "project_image_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "project_image_is_thumbnail" BOOLEAN NOT NULL,
    "project_image_url" CHARACTER VARYING(255) NOT NULL,
    "project_id" BIGINT
);    
ALTER TABLE "PUBLIC"."project_image" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("project_image_id");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.project_image;           
CREATE MEMORY TABLE "PUBLIC"."support_signature"(
    "support_signature_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "member_id" BIGINT NOT NULL,
    "support_signature_content" CHARACTER VARYING(500) NOT NULL,
    "project_id" BIGINT
);      
ALTER TABLE "PUBLIC"."support_signature" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_AB" PRIMARY KEY("support_signature_id");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.support_signature;       
ALTER TABLE "PUBLIC"."project" ADD CONSTRAINT "PUBLIC"."FKe0w7gh0rpmxo35nltk6g8517q" FOREIGN KEY("category_id") REFERENCES "PUBLIC"."category"("category_id") NOCHECK;        
ALTER TABLE "PUBLIC"."project" ADD CONSTRAINT "PUBLIC"."FKcf3xn6841jcaijvqesp19gjox" FOREIGN KEY("maker_id") REFERENCES "PUBLIC"."maker"("maker_id") NOCHECK; 
ALTER TABLE "PUBLIC"."project_image" ADD CONSTRAINT "PUBLIC"."FKsrkbi9ax581cp14a13mbk9qtm" FOREIGN KEY("project_id") REFERENCES "PUBLIC"."project"("project_id") NOCHECK;     
ALTER TABLE "PUBLIC"."product" ADD CONSTRAINT "PUBLIC"."FKncxhj0xapt1bdqasvd92mi1ee" FOREIGN KEY("project_id") REFERENCES "PUBLIC"."project"("project_id") NOCHECK;           
ALTER TABLE "PUBLIC"."support_signature" ADD CONSTRAINT "PUBLIC"."FK34p33d4109n7ix2d8nkmoardo" FOREIGN KEY("project_id") REFERENCES "PUBLIC"."project"("project_id") NOCHECK; 
ALTER TABLE "PUBLIC"."lotdeal" ADD CONSTRAINT "PUBLIC"."FK66bkemghgbquls540w5dhhr80" FOREIGN KEY("project_id") REFERENCES "PUBLIC"."project"("project_id") NOCHECK;           
